config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#home'
  get 'about', to: 'welcome#about'

  get 'tickets/complete', to: 'tickets#complete'

  resources :tickets

  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout' => 'sessions#destroy'
  delete 'logout', to: 'sessions#destroy'
  get '/auth/:provider/callback' => 'sessions#create'

  resources :categories, except: [:destroy] do
    resources :tickets , shallow: true
  end


end

app/models/ticket.rb
class Ticket < ApplicationRecord
    belongs_to :user
    has_many :ticket_categories
    has_many :categories, through: :ticket_categories

    validates :title, presence: true, length: { minimum: 5, maximum: 25 }
    validates :description, presence: true, length: { minimum: 10, maximum: 100 }
    validates :user_id, presence: true


    scope :complete, -> { where(complete: true) }



end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController

    before_action :set_ticket, only: [:edit, :update, :show, :destroy]
    # before_action :set_category, only: [:create, :new]
    before_action :require_user, except: [:index, :show]    
    before_action :require_same_user, only: [:edit, :update, :destroy]

    def index
        @tickets = Ticket.all
    end

    def complete
        @tickets = Ticket.complete
    end

    def new
        @category = Category.find(params[:category_id])
        @ticket = @category.tickets.build
    end

    def edit
       
    end

    def create
        @ticket = Ticket.new(ticket_params)
        @ticket.user = current_user

        if @ticket.save
          flash[:success] = "Ticket was created successfully"
          redirect_to ticket_path(@ticket)
        else
          render 'new'
        end
    end

    def update
        if @ticket.update(ticket_params)
            flash[:success] = "Ticket was successfully updated"
            redirect_to ticket_path(@ticket)
        else
            render 'edit'
        end
    end

    def show
    end

    def destroy
        @ticket.destroy
        flash[:danger] = "Ticket was successfully deleted"
        redirect_to tickets_path
    end

    private

    def set_ticket
        @ticket = Ticket.find(params[:id])
    end

    def set_category
        @category = Category.find(params[:category_id])
    end

    def ticket_params
        params.required(:ticket).permit(:title, :description, :complete, category_ids: [])  
    end

    def require_same_user
        if current_user != @ticket.user and !current_user.agent?
        flash[:danger] = "You can only edit or delete your own tickets"
        redirect_to root_path
        end
    end

end

app/views/tickets/_form.html.erb
<%= render '/shared/errors', obj: @ticket %>
<div class='row'>
    <div class='col-xs-12'>
        <%= form_for([@category, @ticket], :html => { class: "form-horizontal", role: "form" }) do |f| %>
            <div class="form-group">
                <div class="col-sm-8">
                    <%= f.text_field :title, class: "form-control", placeholder: "Title of ticket", autofocus: true  %>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-8">
                    <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Ticket Description" %>
                </div>
            </div>  
            <div class="form-group">
                <div class = "row">
                    <div class="col-sm-offset-2 col-sm-8">
                        <%= f.collection_select :category_ids, Category.all, :id, :name do |cb| %>
                        <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
                        <% end %>
                    </div>
                 </div>  
            </div> 
             <div class="form-group">
                <%= f.label "Ticket Complete" %>
                <%= f.check_box :complete %>
             </div>
            
            <div class="form-group">
                <div class="col-sm-10">
                    <%= f.submit class: 'btn btn-primary btn-lg' %>
                </div>
            </div>
        <% end %>
    </div>
</div>

app/views/tickets/_ticket.html.erb
<% obj.each do |ticket| %>
        <div class="row">
            <div class="col-xs-8 col-xs-offset-2">
                <div class="well well-lg">
                    <div class="ticket-title">
                        <strong>
                            <%= link_to ticket.title, ticket_path(ticket) %>
                        </strong>
                    </div>
                    <div class="ticket-body">
                        <%= truncate(ticket.description, length: 100) %>
                        <div class="ticket-meta-details">
                            <% if ticket.categories.any? %>
                                <p>Categories: <%= render ticket.categories %></p>
                            <% end %>
                             
                            <small>Created by: <%= ticket.user.username if ticket.user %>, 
                                <%= time_ago_in_words(ticket.created_at) %> ago, 
                                last updated: <%= time_ago_in_words(ticket.updated_at) %>
                            </small>
                        </div>
                    </div>
                    <% if logged_in? && (current_user == ticket.user || current_user.agent?) %>
                    <div class="ticket-actions">
                        <%= link_to "Edit", edit_ticket_path(ticket), class: "btn btn-xs btn-primary" %> 
                        <%= link_to "Delete", ticket_path(ticket), method: :delete, 
                                                data: { confirm: "Are you sure you want to delete this ticket?" }, 
                                                class: "btn btn-xs btn-danger" %>
               
           


                        <br>
                    </div>
                    <% end %>
                </div>
            </div>
        </div>
    <% end%>
    

app/views/tickets/complete.html.erb
<h1 align="center">Completed Smartdesk Tickets</h1>

<%= render 'ticket', obj: @tickets %>


app/views/tickets/edit.html.erb
<h1>Edit Existing Ticket</h1>

<%= render 'form' %>

app/views/tickets/index.html.erb
<h1 align="center">All Smartdesk Tickets</h1>

<%= render 'ticket', obj: @tickets %>
    

app/views/tickets/new.html.erb
<h1>Create a Smartdesk Ticket</h1>

<%= render 'form' %>


  

app/views/tickets/show.html.erb
<div class="well col-xs-8 col-xs-offset-2">
    <h4 class="center"><strong><%= @ticket.title %></strong></h4>
    <hr>
    <%= simple_format(@ticket.description) %>
       <% if @ticket.categories.any? %>
            <p>Categories: <%= render @ticket.categories %></p>
        <% end %>
    <div class="ticket-actions">
        <% if logged_in? && (current_user == @ticket.user || current_user.agent?) %>
        <%= link_to "Edit", edit_ticket_path(@ticket), class: "btn btn-xs btn-primary" %> 
        <%= button_to "Delete", ticket_path(@ticket), method: :delete, data: {confirm: "Are you sure you want to delete this ticket?"}, 
        class: "btn btn-xs btn-danger" %>
        <% end %>
    </div>
</div>