config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#home'
  get 'about', to: 'welcome#about'

  get 'tickets/complete', to: 'tickets#complete'

  resources :tickets

  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout' => 'sessions#destroy'
  delete 'logout', to: 'sessions#destroy'
  get '/auth/:provider/callback' => 'sessions#create'

  resources :categories, except: [:destroy] do
    resources :tickets , shallow: true
  end


end

app/models/category.rb
class Category < ApplicationRecord
    has_many :ticket_categories
    has_many :tickets, through: :ticket_categories 
    validates :name, presence: true 
    validates_uniqueness_of :name 
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :require_agent, except:[:index, :show]

    def index
        @categories = Category.all
    end

    def new
        @category = Category.new
    end

    def create 
        @category = Category.new(category_params)
        if @category.save
            flash[:success] = "Smartdesk category was created successfully"
            redirect_to categories_path
        else
            render 'new'
        end
    end

    def show
        @category = Category.find(params[:id])
    end

    def edit
        @category = Category.find(params[:id])
    end

    def update
        @category = Category.find(params[:id])
        if @category.update(category_params)
            flash[:success] = "Smartdesk Category was successfully updated"
            redirect_to category_path(@category)
        else
            render 'edit'
        end
    end    

    private

    def category_params
        params.require(:category).permit(:name)
    end

    def require_agent
        if !logged_in? || (logged_in? and !current_user.agent?)
            flash[:danger] = "Only Smartdesk agents are permitted to do this."
            redirect_to categories_path
        end
    end


end

app/views/categories/_category.html.erb
<span class="category"><%= link_to category.name, category_path(category) %>  </span>
</br>

app/views/categories/_form.html.erb
<%= render '/shared/errors', obj: @category %>


<%= form_for(@category, :html => { class: "form-horizontal", role: "form" }) do |f| %>
    <div class="form-group">
        <div class="control-label col-sm-2">
            <%= f.label :category %>
        </div>
        <div class="col-sm-8">
            <%= f.text_field :name, class: "form-control", placeholder: "Category Name", autofocus: true  %>
        </div>
    </div>
   <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <%= f.submit class: 'btn btn-primary btn-lg' %>
        </div>
    </div>
<% end %>

app/views/categories/edit.html.erb
<h1 align="center">Edit Smartdesk Category</h1>

<%= render 'form' %>

app/views/categories/index.html.erb
<h1 align="center">All Smartdesk Categories</h1>
<div align="center">
<% @categories.each do |category| %>
<ul class="listing">
    <div class="row">
        <div class="well col-md-4 col-md-offset-4">
            <li class="ticket-title">
                <%= render partial: 'category', locals: {category: category }  %>
                <button type="button" class="btn btn-secondary"><%= link_to "Create Ticket", new_category_ticket_path(category) %></button>
                <li><small><%= pluralize(category.tickets.count, "ticket") %></small></li>
            </li>
        </div>
    </div>
</ul>
<% end %>
</div>

app/views/categories/new.html.erb
<h1 align="center">Create a New Smartdesk Category</h1>

<%= render 'form' %>

app/views/categories/show.html.erb
<h1 align="center"><%= @category.name %></h1>

<div align="center">
  <% if logged_in? && current_user.agent? %>
    <div class="row">
      <span class="category"><%= link_to "Edit category name", edit_category_path(@category) %></span>
    </div>
  <% end %>
</div>
