config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#home'
  get 'about', to: 'welcome#about'

  get 'tickets/complete', to: 'tickets#complete'

  resources :tickets

  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout' => 'sessions#destroy'
  delete 'logout', to: 'sessions#destroy'
  get '/auth/:provider/callback' => 'sessions#create'

  resources :categories, except: [:destroy] do
    resources :tickets , shallow: true
  end


end

app/views/layouts/_messages.html.erb
<div class="row">
    <div class="col-xs-10 col-xs-offset-1">
        <% flash.each do |name, message| %>
            <div class='alert alert-<%="#{name}" %>'>
                <a href="#" class="close" data-dismiss="alert">&#215;</a>
                <%= content_tag :div, message, :id => "flash_#{name}" if message.is_a?(String) %>
            </div>
        <% end %>
    </div>
   </div> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Smartdesk</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
       <div class="row">
        <div class="col-md-10 col-md-offset-0">
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                  <ul class="nav navbar-nav">
                      <li><%= link_to "Home", root_path %></li>
                      <% if logged_in? %> 
                        <li><%= link_to "Tickets", tickets_path %></li>
                        <li><%= link_to "Users", users_path %></li>
                         <li><%= link_to "Ticket Categories", categories_path %></li>
                        <li><%= link_to "Create a New Ticket", new_ticket_path %></li>
                        <li><%= link_to "Completed Tickets", tickets_complete_path %></li>
                            <% if current_user.agent? %>
                               <li><%= link_to "Smartdesk Agent", user_path(current_user)%></li>
                            <% else %>
                               <li><%= link_to "My Ticket", user_path(current_user) %></li>
                            <% end %>

                            <% if current_user.agent? %>
                               <li><%= link_to "Create New Smartdesk Category", new_category_path %></li>
                            <% end %>

                        <li><%= link_to "Log out", logout_path, method: :delete %></li>
                      <% else %>
                        <li><%= link_to "About", about_path %></li>
                        <li><%= link_to "Log in", login_path %></li>
                      <% end %>
                  </ul>
            </div>
          </div>
      </div>
</nav>

    <%= render 'layouts/messages' %> 
    <div class="container">
    <%= yield %>
    </div>
  </body>
</html>